$stagingUrl = 'https://wordpress-733947-6451423.cloudwaysapps.com'
$blogDir = 'C:\Users\moham\ruladiet-site\blog'

Write-Output "=========================================="
Write-Output "  RULA DIET - VERCEL TO WORDPRESS MIGRATION"
Write-Output "  Staging: $stagingUrl"
Write-Output "=========================================="
Write-Output ""
Write-Output "=== STAGING PAGES ==="
Write-Output "1. Homepage:        $stagingUrl/"
Write-Output "2. Team (من نحن):   $stagingUrl/team/"
Write-Output "3. Appointment:     $stagingUrl/appointment/"
Write-Output ""
Write-Output "=== BLOG POSTS ==="
Write-Output "1. رمضان بلا سكر:  $stagingUrl/ramadan-without-sugar/"
Write-Output "2. المهمة الممكنة: $stagingUrl/new-year-mission/"
Write-Output "3. المهمة المستحيلة: $stagingUrl/impossible-mission-moms/"
Write-Output "4. إبر التنحيف:    $stagingUrl/ابر-التنحيف-الحديثة/"
Write-Output ""
Write-Output "=== MEDIA UPLOADED ==="
Write-Output "Hero image:     ID 11388"
Write-Output "Course images:  IDs 11389-11392"
Write-Output "Author image:   ID 11394"
Write-Output ""
Write-Output "=== CSS ==="
Write-Output "Code Snippet ID 11 active - reads /wp-content/uploads/2026/05/all-css.txt"
Write-Output ""
Write-Output "=== NEWSLETTER ==="
Write-Output "MC4WP form ID 10484 rendering on homepage"
Write-Output ""
Write-Output "=== PUSH TO LIVE ==="
Write-Output "Next: Go to Cloudways → Staging Management → Push to Live"
Write-Output "Then verify all URLs work on live site (ruladiet.com)"
Write-Output ""
Write-Output "=== KNOWN ISSUES ==="
Write-Output "- Blog posts have duplicate H1 (WoodMart theme title + custom title)"
Write-Output "- Newsletter form uses MC4WP default styling (not custom green theme)"
Write-Output "- Blog sidebar links point to other blog posts (internal linking)"
Write-Output "- Course cards on homepage still link to courses.ruladiet.com"
Write-Output ""
Write-Output "=========================================="
